language: android

jdk:
  oraclejdk8

env:
  global:
    - ANDROID_SDK_VERSION="r24.0.2"
    - BUILD_TOOLS="21.1.2"
    - TARGET_API="22"

android:
  components:
    - build-tools-${BUILD_TOOLS}  # specify build tools version as they might not be pre-installed
    - android-${TARGET_API}  # The SDK version used to compile your project

  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

before_install:
  # environment info
  - uname -a

  # for gradle output style
  - export TERM=dumb

install:
  ./gradlew clean assembleDebug test
